name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        cfg: [Debug, Release]
    env:
      CFG: ${{ matrix.cfg }}
    defaults:
      run:
        shell: cmd
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Cache object files
        id: windows-cache
        uses: actions/cache@v3
        with:
          path: |
            D:/a/wesnoth/wesnoth/vcpkg_installed
          key: win-cache-master-${{ matrix.cfg }}-0002

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.20.6'
# checkout a specific commit to prevent cmake from thinking it can't use the cached dependencies anymore
# the commit itself is just whatever happens to be the latest commit when a newer version is needed
      - name: Build vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg D:/a/wesnoth/vcpkg
          git clone -b graph-debug --single-branch --depth 1 https://github.com/dan-shaw/vcpkg-tool D:/a/wesnoth/vcpkg-tool
          cd D:/a/wesnoth/vcpkg-tool
          git switch graph-debug
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
          cmake --build .
          dir Debug
          cp D:/a/wesnoth/vcpkg-tool/build/Debug/vcpkg.exe D:/a/wesnoth/vcpkg/vcpkg.exe
          cd D:/a/wesnoth/vcpkg
      - name: Run cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=%CFG% -DENABLE_GAME=true -DENABLE_SERVER=true -DENABLE_CAMPAIGN_SERVER=true -DENABLE_TESTS=true -DENABLE_MYSQL=false -DENABLE_NLS=false -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_INSTALL_OPTIONS="--debug;--dry-run" -DCMAKE_TOOLCHAIN_FILE=D:/a/wesnoth/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR_PLATFORM=x64 -G "Visual Studio 17 2022" .

# delete buildtrees directory to free up space after cmake invokes vcpkg to build the dependencies
# otherwise the job was failing when trying to write a .obj file
# building vcpkg on the more spacious C drive didn't work since for some reason vcpkg decides to not create the pango/cairo pkgconfig files there
      - name: Build wesnoth, wesnothd, campaignd and unit tests
        run: |
          rmdir /s /q D:\a\wesnoth\vcpkg\buildtrees
          MSBuild.exe wesnoth.sln -p:Configuration=%CFG%

      - name: Run WML unit tests
        if: matrix.cfg == 'Release'
        run: python run_wml_tests -v -g -c -t 20 -p D:/a/wesnoth/wesnoth/%CFG%/wesnoth.exe
